version: 0.9.0+{build}

image:
- Visual Studio 2017

install:
- cinst swig
- curl -L http://prdownloads.sourceforge.net/scons/scons-3.0.1.zip --output scons-3.0.1.zip
- 7z x scons-3.0.1.zip
- cd scons-3.0.1
- python setup.py install

build_script:
- cd C:\projects\dps-for-iot
- scons SWIG=swig
