sudo: required

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - doxygen
      - g++-7
      - zlib1g-dev

compiler:
  - gcc

env:
  - CC=gcc-7 CXX=g++-7 VARIANT=debug TRANSPORT=udp
  - CC=gcc-7 CXX=g++-7 VARIANT=debug TRANSPORT=tcp
  - CC=gcc-7 CXX=g++-7 VARIANT=debug TRANSPORT=dtls
  - CC=gcc-7 CXX=g++-7 VARIANT=release TRANSPORT=udp
  - CC=gcc-7 CXX=g++-7 VARIANT=release TRANSPORT=tcp
  - CC=gcc-7 CXX=g++-7 VARIANT=release TRANSPORT=dtls

before_install:
  - eval "CC=gcc-7 && CXX=g++-7"
  - ./.travis/install-swig.sh
  - ./.travis/install-nodejs.sh

language: c

script:
  - scons variant=$VARIANT transport=$TRANSPORT CC=$CC CXX=$CXX UV_PATH=ext/libuv
