sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - g++-7
            - zlib1g-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

env:
  - VARIANT=debug
  - VARIANT=release

env:
  - TRANSPORT=udp
  - TRANSPORT=tcp
  - TRANSPORT=dtls

compiler:
  - gcc

before_install:
  - eval "${MATRIX_EVAL}"
  - ./.travis/install-swig.sh
  - ./.travis/install-nodejs.sh

language: c
script: scons variant=$VARIANT transport=$TRANSPORT CC=$CC CXX=$CXX UV_PATH=ext/libuv
