sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - doxygen
            - g++-7
            - zlib1g-dev
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

compiler:
  - gcc

env:
  - ${MATRIX_EVAL} VARIANT=debug TRANSPORT=udp
  - ${MATRIX_EVAL} VARIANT=debug TRANSPORT=tcp
  - ${MATRIX_EVAL} VARIANT=debug TRANSPORT=dtls
  - ${MATRIX_EVAL} VARIANT=release TRANSPORT=udp
  - ${MATRIX_EVAL} VARIANT=release TRANSPORT=tcp
  - ${MATRIX_EVAL} VARIANT=release TRANSPORT=dtls

before_install:
  - eval "${MATRIX_EVAL}"
  - ./.travis/install-swig.sh
  - ./.travis/install-nodejs.sh

language: c

script:
  - scons variant=$VARIANT transport=$TRANSPORT CC=$CC CXX=$CXX UV_PATH=ext/libuv
